# Generated by Django 4.0.3 on 2024-09-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backgroundImage',
            field=models.ImageField(blank=True, default='background.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
