# Generated by Django 4.0.3 on 2024-09-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_people_you_may_know_user_posts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
